branches:
  except:
  - /^gh-pages(-.*)?$/

environment:
  NOCODECHECKS: "true"
  matrix:
  - PYTHON: "C:\\Python35"
  - PYTHON: "C:\\Python35-x64"
  - PYTHON: "C:\\Python36"
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python37"
  - PYTHON: "C:\\Python37-x64"
  - PYTHON: "C:\\Python38"
  - PYTHON: "C:\\Python38-x64"

build: off

install:
- ps: |
    echo "Available Python versions:"
    ls "C:/" | Select-String -Pattern "Python*"
    echo ""
    echo "Installed SDKs:"
    ls "C:/Program Files/Microsoft SDKs/Windows"
    if (-not(Test-Path($env:PYTHON))) {
      & appveyor\install.ps1
    }
- |
  SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  python --version
  python -c "import struct; print(struct.calcsize('P') * 8)"
  pip install --disable-pip-version-check --user --upgrade pip setuptools wheel

test_script:
- python setup.py test
