language: python

addon:
  apt:
    nodejs

matrix:
  include:
  - python: "2.7"
  - python: "pypy"
  - python: "pypy3"
  - python: "3.3"
    env:
    - legacy=yes
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    env:
    - eslint=yes
    - sphinx=yes

install:
  - |
    if [ "$legacy" != "yes" ]; then
      pip install --upgrade pip setuptools
    fi
  - pip install -r requirements/ci.txt
  - pip install .
  - |
    if [ "$eslint" = "yes" ]; then
      nvm install stable
      nvm use stable
      npm install eslint
    fi
  - |
    if [ "$sphinx" = "yes" ]; then
      pip install -r requirements/doc.txt
    fi

script:
  - coverage run setup.py test
  - coverage report
  - |
    if [ "$eslint" = "yes" ]; then
      node_modules/.bin/eslint browsepy
    fi
  - |
    if [ "$sphinx" = "yes" ]; then
      make -C doc html
    fi

after_success:
  - codecov
  - coveralls
  - |
    if [ "$sphinx" = "yes" ] && \
       [ "$TRAVIS_BRANCH" = "master" ] && \
       [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      ghp-import \
        --push \
        --force \
        --no-jekyll \
        --branch=gh-pages \
        --remote="https://${GH_TOKEN}@github.com${TRAVIS_REPO_SLUG}.git" \
        doc/.build/html
    fi

notifications:
  email: false

cache:
  directories:
    - $HOME/.cache/pip
